### PR TITLE
Fix check updates feature

### PR DESCRIPTION
**Pull request by fjcapdevila**
check_update method wasn't working, probably because conda output changed.

### CODE REVIEW

**Comment by fjcapdevila** [comment]
I repaired the backend, but now the frontend doesn't do anything with the results.

**Comment by damianavila** [comment]
> I repaired the backend, but now the frontend doesn't do anything with the results.

OK... then we need to look into JS part :wink:

**Comment by fjcapdevila** [comment]
> we need to look into JS part

I fixed the issue in JS.

**Comment by damianavila** [comment]
As a follow up, if we want to put this on the next AEN release we need to:

* release nb_conda and upgrade nb_conda version in recipes

or

* upgrade nb_conda patch in recipes containing the fix.

Second option is probably more quick and easy for now.

**Pull request merged**
