### PR TITLE
Update kernel regex

### PR DESCRIPTION
**Pull request by bollwyvl**
For #27.

This updates:
- the notebook conda dialog to correctly identify the current environment, based on `nb_conda_kernels 2.0.0`
- some minor visual fixes
- some more basic tests
- uses requirements.txt instead of environment.yml for tests, etc.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Blocked by:
https://github.com/conda-forge/tornado-feedstock/pull/7

**Comment by bollwyvl** [comment]
Hot dang, all 💚 ! Actually went and checked the appveyor builds, as i didn't really believe it... whaddya know, lots of ".trash ain't empty" messages. Just like the bad old days. But everything worked. So I'll take it.

Review love appreciated, @damianavila @mmarchetti @malev or anybody else you guys can think of that have spent time on this on. ended up being rather large.

**Comment by mmarchetti** [comment]
I did a brief review... +1 on the addition of tests!

**Comment by damianavila** [comment]
Quick overview as well, but this look nice... I like some of the simplifications I saw and obviously the tests are a great addition. Wondering why you decide to use the APIHandler + Mixin instead of continuing with the EnvHandler. I like the approach you took but this is something derived from other work, or other extensions you wrote/saw or just you saw the opportunity to make this way and did it?

**Comment by bollwyvl** [comment]
> Wondering why you decide to use the APIHandler + Mixin instead of continuing with the EnvHandler

Kind of a leftover... i was looking at whether there needed to be a separate handler for some of the end points, but it didn't. I'll simplify it back down.

**Comment by bollwyvl** [comment]
Ok, back to the simpler inheritance pattern! `__mro__`-begone!

**Comment by bollwyvl** [comment]
Ok, liking this! I'm going to merge and tag!

**Pull request merged**
