### PR TITLE
WIP: Update extension to the proposed mechanism in PR 879

### PR DESCRIPTION
**Pull request by damianavila**
This is tied to https://github.com/Anaconda-Server/anaconda-nb-extensions/issues/148

### CODE REVIEW

**Comment by damianavila** [comment]
This was updated up to the notebook 4.2 beta1... tests will fail until we have https://github.com/Anaconda-Server/nb_conda_kernels/pull/20 merged and the packages build... alternative I can build from the PR and put in in the dev channel...

**Comment by bollwyvl** [comment]
Started on this!

**Comment by damianavila** [comment]
Same comments as the other `nb_conda_kernels` PR about not using `setuptools` if we can avoid it... otherwise, it is the same pattern as the other PR... so I am OK with that...

**Comment by bollwyvl** [comment]
Beta builds are up:
https://anaconda.org/anaconda-nb-extensions/nb_conda/files?version=1.0.0b1

**Pull request merged**
