### PR TITLE
bring conda list --json interface up to date with conda 4.3

### LINKED ISSUE #39: unhandled AttributeError on listing current env
When trying to use the _Kernel->Conda Packages_ menu entry provided by nb_conda, I'm encountering the following unhandled exception:
```
[E 17:32:30.477 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/sarc/spa/users/tsnyder/.conda/envs/cat-1/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/sarc/spa/users/tsnyder/.conda/envs/cat-1/lib/python3.5/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/sarc/spa/users/tsnyder/.conda/envs/cat-1/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/sarc/spa/users/tsnyder/.conda/envs/cat-1/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in <listcomp>
        "packages": [pkg_info(package) for package in data]
      File "/sarc/spa/users/tsnyder/.conda/envs/cat-1/lib/python3.5/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
```
[cat-1.yaml.txt](https://github.com/Anaconda-Platform/nb_conda/files/709637/cat-1.yaml.txt) is the output of _conda env export_ for my environment.  Before filing this ticket, I also had @groutr repro the behavior.

### PR DESCRIPTION
**Pull request by kalefranz**
resolves #39

### CODE REVIEW

**Comment by kalefranz** [comment]
#43, which is just a current build of master, shows the same build errors as this PR.  This PR should be good to merge.

**Comment by damianavila** [comment]
Thanks for the PR @kalefranz!

**Comment by bearnshaw** [comment]
Any reason why this hasn't been merged yet?  Would love to use nb_conda again without all the errors.

**Comment by chrislaing** [comment]
Any update on when this might be merged?

**Comment by MichaelJAndy** [comment]
Was bitten by this one today, any further updates?

This is a guide on how to work around this: http://stackoverflow.com/questions/41678162/anaconda3-attributeerror-dict-object-has-no-attribute-rsplit

**Comment by damianavila** [comment]
This will be tested, merged and shipped in the next few weeks.

**Comment by damianavila** [comment]
Tested locally, so merging. Fixing test in a upcoming PR.

**Comment by damianavila** [comment]
Thank you @kalefranz

**Comment by rbhatia5** [comment]
Any timeline on the release?

**Comment by damianavila** [comment]
@rbhatia5, working on the release this week.

**Pull request merged**
